version: '3'
services:
  db:
    image: mysql:5.7.27
    # restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  backend:
    build: ./backend
    ports:
      - ${BACKEND_PORT}:3000
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -b ${BACKEND_HOST}"
    volumes:
      - ./backend:/app
      - backend-bundle:/usr/local/bundle
    environment:
      - HOST=${BACKEND_HOST}
      - PORT=${BACKEND_PORT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - RAILS_ENV=production
    depends_on:
      - db
    tty: true
    stdin_open: true
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prd
    ports:
      - ${FRONTEND_PORT}:8080
    command: /bin/sh -c "yarn start"
    volumes:
      - ./frontend:/app
      - frontend-node_modules:/app/node_modules
    environment:
      - HOST=${FRONTEND_HOST}
      - PORT=${FRONTEND_PORT}
      - NODE_ENV=production
      - gnavi_api_key=${GNAVI_API_KEY}
      - gmap_api_key=${GMAP_API_KEY}
    tty: true
volumes:
  db-data:
  backend-bundle:
  frontend-node_modules: